<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="IHost.fs" />
    <Compile Include="SymbolTable.fs" />
    <Compile Include="Analyzer/Semantic.fs" />
    <Compile Include="Prelude/Builtins.fs" />
    <Compile Include="Interpreter.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RobLang.Parser\RobLang.Parser.fsproj" />
  </ItemGroup>

</Project>
